; PlatformIO Project Configuration File
;
; Board: change "esp32dev" below if you're using a different exact
; ESP32 board variant. Run `pio boards esp32` in a terminal to search.

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = huge_app.csv
build_flags =
    -D CONFIG_MBEDTLS_CERTIFICATE_BUNDLE=1
upload_port = COM3
monitor_speed = 115200
lib_deps =
    bblanchon/ArduinoJson
    oxullo/MAX30100lib
    adafruit/Adafruit MPU6050
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit BusIO
    paulstoffregen/OneWire
    milesburton/DallasTemperature
    mikalhart/TinyGPSPlus
